import json
from datetime import datetime
from html import escape
from pathlib import Path
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


class ShortlistPDFGenerator:
    REPORT_SECTIONS_PATH = Path("app/temp/candidate_report_sections.json")
    OUTPUT_DIR = Path("app/output")
    OUTPUT_FILE = "github_candidate_shortlist.pdf"

    CREATOR = "Erich Johannes Wessel"
    PROJECT_NAME = "recruitment-pipeline-os"
    REPOSITORY_URL = "https://github.com/wessel05j/recruitment-pipeline-os"

    def run(self) -> Path:
        report = self._load_report_sections()
        self.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        output_path = self.OUTPUT_DIR / self.OUTPUT_FILE

        self._build_pdf(report=report, output_path=output_path)
        print(f"PDF shortlist saved to: {output_path}")
        return output_path

    def _load_report_sections(self) -> Dict[str, Any]:
        if not self.REPORT_SECTIONS_PATH.exists():
            raise FileNotFoundError(
                f"Missing candidate report sections: {self.REPORT_SECTIONS_PATH}"
            )

        return json.loads(self.REPORT_SECTIONS_PATH.read_text(encoding="utf-8"))

    def _build_pdf(self, report: Dict[str, Any], output_path: Path) -> None:
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=18 * mm,
            leftMargin=18 * mm,
            topMargin=18 * mm,
            bottomMargin=18 * mm,
            title=report.get("report_title", "GitHub Candidate Shortlist"),
            author=self.CREATOR,
        )

        styles = self._styles()
        story = self._build_story(report, styles)
        doc.build(story, onFirstPage=self._footer, onLaterPages=self._footer)

    def _build_story(
        self,
        report: Dict[str, Any],
        styles: Dict[str, ParagraphStyle],
    ) -> List[Any]:
        candidates = report.get("candidates", [])
        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

        story: List[Any] = [
            Paragraph(self._text(report.get("report_title", "GitHub Candidate Shortlist")), styles["title"]),
            Spacer(1, 5 * mm),
            Paragraph(
                f"Generated by {self.PROJECT_NAME} on {self._text(generated_at)}",
                styles["muted_center"],
            ),
            Spacer(1, 7 * mm),
            Paragraph(self._text(report.get("role_summary", "Role summary not available.")), styles["body"]),
            Spacer(1, 8 * mm),
            self._summary_table(report, styles),
            Spacer(1, 8 * mm),
            Paragraph("Candidate Ranking", styles["section"]),
            Spacer(1, 3 * mm),
            self._ranking_table(candidates, styles),
        ]

        for candidate in candidates:
            story.append(PageBreak())
            story.extend(self._candidate_section(candidate, styles))

        return story

    def _summary_table(
        self,
        report: Dict[str, Any],
        styles: Dict[str, ParagraphStyle],
    ) -> Table:
        data = [
            [
                Paragraph("Source", styles["table_label"]),
                Paragraph("GitHub", styles["table_value"]),
                Paragraph("Candidates", styles["table_label"]),
                Paragraph(str(report.get("candidate_count", 0)), styles["table_value"]),
            ],
            [
                Paragraph("Created by", styles["table_label"]),
                Paragraph(self.CREATOR, styles["table_value"]),
                Paragraph("Repository", styles["table_label"]),
                Paragraph(self.REPOSITORY_URL, styles["table_value"]),
            ],
        ]

        table = Table(data, colWidths=[28 * mm, 55 * mm, 28 * mm, 55 * mm])
        table.setStyle(self._base_table_style())
        return table

    def _ranking_table(
        self,
        candidates: List[Dict[str, Any]],
        styles: Dict[str, ParagraphStyle],
    ) -> Table:
        data = [
            [
                Paragraph("Rank", styles["table_header"]),
                Paragraph("Candidate", styles["table_header"]),
                Paragraph("Score", styles["table_header"]),
                Paragraph("Contact", styles["table_header"]),
                Paragraph("Recommendation", styles["table_header"]),
            ]
        ]

        for candidate in candidates:
            contactability = candidate.get("contactability", {})
            data.append(
                [
                    Paragraph(str(candidate.get("rank", "")), styles["table_value"]),
                    Paragraph(self._text(candidate.get("display_name", "Unknown")), styles["table_value"]),
                    Paragraph(str(candidate.get("score", "")), styles["table_value"]),
                    Paragraph(self._text(contactability.get("label", "NONE")), styles["table_value"]),
                    Paragraph(self._text(candidate.get("recommendation", "")), styles["table_value"]),
                ]
            )

        if len(data) == 1:
            data.append(
                [
                    Paragraph("-", styles["table_value"]),
                    Paragraph("No candidates passed admin review.", styles["table_value"]),
                    Paragraph("-", styles["table_value"]),
                    Paragraph("-", styles["table_value"]),
                    Paragraph("-", styles["table_value"]),
                ]
            )

        table = Table(data, colWidths=[16 * mm, 63 * mm, 20 * mm, 25 * mm, 42 * mm])
        table.setStyle(self._base_table_style(header=True))
        return table

    def _candidate_section(
        self,
        candidate: Dict[str, Any],
        styles: Dict[str, ParagraphStyle],
    ) -> List[Any]:
        contactability = candidate.get("contactability", {})
        profile = candidate.get("profile", {})
        evidence = candidate.get("github_evidence", {})

        story: List[Any] = [
            Paragraph(
                f"#{candidate.get('rank', '')} {self._text(candidate.get('display_name', 'Unknown'))}",
                styles["candidate_title"],
            ),
            Spacer(1, 2 * mm),
            Paragraph(self._text(candidate.get("headline", "")), styles["muted"]),
            Spacer(1, 5 * mm),
            self._candidate_meta_table(candidate, profile, contactability, styles),
            Spacer(1, 6 * mm),
            Paragraph("Technical Fit", styles["section"]),
            Paragraph(
                self._text(candidate.get("technical_fit_summary", "No summary available.")),
                styles["body"],
            ),
            Spacer(1, 4 * mm),
            Paragraph("Why Selected", styles["subsection"]),
            self._bullet_list(candidate.get("why_selected", []), styles),
            Spacer(1, 4 * mm),
            Paragraph("Possible Concerns", styles["subsection"]),
            self._bullet_list(candidate.get("possible_concerns", []), styles),
            Spacer(1, 4 * mm),
            Paragraph("GitHub Evidence", styles["section"]),
            self._evidence_table(evidence, styles),
            Spacer(1, 4 * mm),
            Paragraph("Notable Repositories", styles["subsection"]),
            self._repo_table(evidence.get("notable_repositories", []), styles),
        ]

        return story

    def _candidate_meta_table(
        self,
        candidate: Dict[str, Any],
        profile: Dict[str, Any],
        contactability: Dict[str, Any],
        styles: Dict[str, ParagraphStyle],
    ) -> Table:
        data = [
            [
                Paragraph("GitHub", styles["table_label"]),
                Paragraph(self._text(candidate.get("github_profile_url", "Not listed")), styles["table_value"]),
            ],
            [
                Paragraph("Location", styles["table_label"]),
                Paragraph(self._text(profile.get("location", "Not listed")), styles["table_value"]),
            ],
            [
                Paragraph("Company", styles["table_label"]),
                Paragraph(self._text(profile.get("company", "Not listed")), styles["table_value"]),
            ],
            [
                Paragraph("Public email", styles["table_label"]),
                Paragraph(self._text(profile.get("public_email", "No public email found")), styles["table_value"]),
            ],
            [
                Paragraph("Contactability", styles["table_label"]),
                Paragraph(
                    self._text(
                        f"{contactability.get('label', 'NONE')} ({contactability.get('score', 0)}/100) - "
                        f"{contactability.get('note', 'No contactability note.')}"
                    ),
                    styles["table_value"],
                ),
            ],
        ]

        table = Table(data, colWidths=[34 * mm, 132 * mm])
        table.setStyle(self._base_table_style())
        return table

    def _evidence_table(
        self,
        evidence: Dict[str, Any],
        styles: Dict[str, ParagraphStyle],
    ) -> Table:
        signal_matches = evidence.get("signal_matches", [])

        if isinstance(signal_matches, list):
            signal_text = ", ".join(str(item) for item in signal_matches) or "No signal matches listed"
        else:
            signal_text = str(signal_matches)

        data = [
            [
                Paragraph("Languages", styles["table_label"]),
                Paragraph(", ".join(evidence.get("matched_languages", [])) or "Not listed", styles["table_value"]),
            ],
            [
                Paragraph("Signal matches", styles["table_label"]),
                Paragraph(self._text(signal_text), styles["table_value"]),
            ],
        ]

        table = Table(data, colWidths=[34 * mm, 132 * mm])
        table.setStyle(self._base_table_style())
        return table

    def _repo_table(
        self,
        repositories: List[Dict[str, Any]],
        styles: Dict[str, ParagraphStyle],
    ) -> Table:
        data = [
            [
                Paragraph("Repository", styles["table_header"]),
                Paragraph("Language", styles["table_header"]),
                Paragraph("Stars", styles["table_header"]),
                Paragraph("Description", styles["table_header"]),
            ]
        ]

        for repo in repositories[:5]:
            data.append(
                [
                    Paragraph(self._text(repo.get("name", "Unknown")), styles["table_value"]),
                    Paragraph(self._text(repo.get("language", "Not listed")), styles["table_value"]),
                    Paragraph(str(repo.get("stars", "")), styles["table_value"]),
                    Paragraph(self._text(repo.get("description", "Not listed")), styles["table_value"]),
                ]
            )

        if len(data) == 1:
            data.append(
                [
                    Paragraph("-", styles["table_value"]),
                    Paragraph("-", styles["table_value"]),
                    Paragraph("-", styles["table_value"]),
                    Paragraph("No notable repositories listed.", styles["table_value"]),
                ]
            )

        table = Table(data, colWidths=[42 * mm, 27 * mm, 17 * mm, 80 * mm])
        table.setStyle(self._base_table_style(header=True))
        return table

    def _bullet_list(
        self,
        items: List[str],
        styles: Dict[str, ParagraphStyle],
    ) -> ListFlowable:
        if not items:
            items = ["Not listed."]

        return ListFlowable(
            [
                ListItem(Paragraph(self._text(item), styles["body"]), leftIndent=4 * mm)
                for item in items
            ],
            bulletType="bullet",
            leftIndent=6 * mm,
        )

    def _styles(self) -> Dict[str, ParagraphStyle]:
        base = getSampleStyleSheet()
        body = base["BodyText"]
        body.fontName = "Helvetica"
        body.fontSize = 9.5
        body.leading = 13
        body.textColor = colors.HexColor("#1F2933")

        return {
            "title": ParagraphStyle(
                "Title",
                parent=body,
                fontName="Helvetica-Bold",
                fontSize=24,
                leading=29,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#102A43"),
                spaceAfter=4 * mm,
            ),
            "candidate_title": ParagraphStyle(
                "CandidateTitle",
                parent=body,
                fontName="Helvetica-Bold",
                fontSize=18,
                leading=22,
                textColor=colors.HexColor("#102A43"),
            ),
            "section": ParagraphStyle(
                "Section",
                parent=body,
                fontName="Helvetica-Bold",
                fontSize=12,
                leading=15,
                textColor=colors.HexColor("#243B53"),
                spaceBefore=2 * mm,
                spaceAfter=2 * mm,
            ),
            "subsection": ParagraphStyle(
                "Subsection",
                parent=body,
                fontName="Helvetica-Bold",
                fontSize=10,
                leading=13,
                textColor=colors.HexColor("#334E68"),
                spaceAfter=1 * mm,
            ),
            "body": body,
            "muted": ParagraphStyle(
                "Muted",
                parent=body,
                textColor=colors.HexColor("#627D98"),
            ),
            "muted_center": ParagraphStyle(
                "MutedCenter",
                parent=body,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#627D98"),
            ),
            "table_header": ParagraphStyle(
                "TableHeader",
                parent=body,
                fontName="Helvetica-Bold",
                fontSize=8.5,
                leading=11,
                textColor=colors.white,
            ),
            "table_label": ParagraphStyle(
                "TableLabel",
                parent=body,
                fontName="Helvetica-Bold",
                fontSize=8.5,
                leading=11,
                textColor=colors.HexColor("#334E68"),
            ),
            "table_value": ParagraphStyle(
                "TableValue",
                parent=body,
                fontSize=8.5,
                leading=11,
                textColor=colors.HexColor("#1F2933"),
                wordWrap="CJK",
            ),
            "footer": ParagraphStyle(
                "Footer",
                parent=body,
                fontSize=7.5,
                alignment=TA_RIGHT,
                textColor=colors.HexColor("#829AB1"),
            ),
        }

    def _base_table_style(self, header: bool = False) -> TableStyle:
        commands = [
            ("BOX", (0, 0), (-1, -1), 0.35, colors.HexColor("#D9E2EC")),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D9E2EC")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("BACKGROUND", (0, 0), (-1, -1), colors.white),
        ]

        if header:
            commands.append(("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#243B53")))

        return TableStyle(commands)

    def _footer(self, canvas: Any, doc: SimpleDocTemplate) -> None:
        canvas.saveState()
        width, _ = A4
        footer_text = f"{self.PROJECT_NAME} | {self.REPOSITORY_URL} | page {doc.page}"
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(colors.HexColor("#829AB1"))
        canvas.drawRightString(width - 18 * mm, 10 * mm, footer_text)
        canvas.restoreState()

    def _text(self, value: Any) -> str:
        if value is None or value == "":
            return ""

        return escape(str(value))
